import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./AuthProvider";

import { Roboto } from "next/font/google";
import LoaderGlobal from "@/components/LoaderGlobal";

// Initialize the font
const roboto = Roboto({
  subsets: ["latin"], // Supports Latin characters
  weight: ["400", "700"], // Choose weights (400 = Regular, 700 = Bold)
  style: ["normal", "italic"], // Choose styles
  variable: "--font-roboto", // (Optional) Custom CSS variable for Tailwind or global styles
});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Bird_Blog",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body
       className={roboto.className}
      >
        
       <AuthProvider>
        <LoaderGlobal/>
       <Navbar/>
        {children}
        <Footer/>
        <Toaster />
       </AuthProvider>
      </body>
    </html>
  );
}
